name: Generate Snake Game

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Generate Snake Game
        uses: Platane/snk@master
        with:
          github_user_name: 'sainavaneet'
          outputs: 'dist/github-snake.svg'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          publish_dir: ./dist
